services:
  database:
    container_name: rubin-zonen-database
    image: postgres
    env_file:
      - .env
    environment:
      POSTGRES_USER : ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql
volumes:
  db-data: