- name: Create Azure VM
  hosts: localhost
  connection: local
  tasks:
  - name: Delete resource group
    azure.azcollection.azure_rm_resourcegroup:
        name: "VM_rg"
        location: "France Central"
        state: absent
    register: rg_result

  - name: Create resource group
    azure_rm_resourcegroup:
      name: VM_rg
      location: eastus

  - name: Create virtual network
    azure_rm_virtualnetwork:
      resource_group: VM_rg
      name: myVnet
      address_prefixes: "10.0.0.0/16"

  - name: Add subnet
    azure_rm_subnet:
      resource_group: VM_rg
      name: mySubnet
      address_prefix: "10.0.1.0/24"
      virtual_network: myVnet

  - name: Create public IP address
    azure_rm_publicipaddress:
      resource_group: VM_rg
      allocation_method: Static
      name: myPublicIP
    register: output_ip_address

  - name: Public IP of VM
    debug:
      msg: "The public IP is {{ output_ip_address.state.ip_address }}."

  - name: Create virtual network interface card
    azure_rm_networkinterface:
      resource_group: VM_rg
      name: myNIC
      virtual_network: myVnet
      subnet: mySubnet
      public_ip_name: myPublicIP
      security_group: myNetworkSecurityGroup

  - name: Create VM
    azure_rm_virtualmachine:
      resource_group: VM_rg
      name: myVM
      vm_size: Standard_DS1_v2
      admin_username: azureuser
      admin_password: "password!"
      ssh_password_enabled: true
      network_interfaces: myNIC
      image:
        offer: 0001-com-ubuntu-server-jammy
        publisher: Canonical
        sku: 22_04-lts
        version: latest